version: "3.8"

services:
  ultrafeeder:
    image: ghcr.io/sdr-enthusiasts/docker-adsb-ultrafeeder
    # image: ghcr.io/sdr-enthusiasts/docker-adsb-ultrafeeder:telegraf
    container_name: ultrafeeder
    hostname: ultrafeeder
    device_cgroup_rules:
      - "c 189:* rwm"
    ports:
      - "127.0.0.1:8080:80"
      # to expose the statistics interface to Prometheus
      - "127.0.0.1:9273-9274:9273-9274"
    environment:
      - LOGLEVEL=${LOGLEVEL-verbose}
      - TZ="Asia/Kolkata"
      # SDR related parameters:
      - READSB_DEVICE_TYPE=rtlsdr
      - READSB_GAIN=auto
      - READSB_RTLSDR_DEVICE=${ADSB_SDR_SERIAL}
      - READSB_RTLSDR_PPM=${ADSB_SDR_PPM}
      # readsb/decoder parameters:
      - READSB_LAT=12.9249224
      - READSB_LON=77.6642962
      - READSB_ALT=26m
      - READSB_RX_LOCATION_ACCURACY=2
      - READSB_STATS_RANGE=true
      # Sources and Aggregator connections:
      - ULTRAFEEDER_CONFIG=
        adsb,feed.adsb.fi,30004,beast_reduce_plus_out;
        adsb,in.adsb.lol,30004,beast_reduce_plus_out;
        adsb,feed.airplanes.live,30004,beast_reduce_plus_out;
        adsb,feed.planespotters.net,30004,beast_reduce_plus_out;
        adsb,feed.theairtraffic.com,30004,beast_reduce_plus_out;
        adsb,data.avdelphi.com,24999,beast_reduce_plus_out;
        adsb,skyfeed.hpradar.com,30004,beast_reduce_plus_out;
        adsb,dati.flyitalyadsb.com,4905,beast_reduce_plus_out;
        mlat,feed.adsb.fi,31090,39000;
        mlat,in.adsb.lol,31090,39001;
        mlat,feed.airplanes.live,31090,39002;
        mlat,mlat.planespotters.net,31090,39003;
        mlat,feed.theairtraffic.com,31090,39004;
        mlat,skyfeed.hpradar.com,31090,39005;
        mlat,dati.flyitalyadsb.com,30100,39007;
      # If you really want to feed ADSBExchange, you can do so by adding this above:
      #        adsb,feed1.adsbexchange.com,30004,beast_reduce_plus_out,uuid=${ADSBX_UUID};
      #        mlat,feed.adsbexchange.com,31090,39008,uuid=${ADSBX_UUID}
      - UUID=61c794ea-a5c1-448f-b2f2-ea289f217bcc
      - MLAT_USER=vizpi
      # TAR1090 (Map Web Page) parameters:
      - UPDATE_TAR1090=true
      - TAR1090_MESSAGERATEINTITLE=true
      - TAR1090_PAGETITLE=vizpi
      - TAR1090_PLANECOUNTINTITLE=true
      - TAR1090_ENABLE_AC_DB=true
      - TAR1090_FLIGHTAWARELINKS=true
      - HEYWHATSTHAT_PANORAMA_ID=${FEEDER_HEYWHATSTHAT_ID}
      - HEYWHATSTHAT_ALTS=${FEEDER_HEYWHATSTHAT_ALTS}
      - TAR1090_SITESHOW=true
      - TAR1090_RANGE_OUTLINE_COLORED_BY_ALTITUDE=true
      - TAR1090_RANGE_OUTLINE_WIDTH=2.0
      - TAR1090_RANGERINGSDISTANCES=50,100,150,200
      - TAR1090_RANGERINGSCOLORS='#1A237E','#0D47A1','#42A5F5','#64B5F6'
      - TAR1090_USEROUTEAPI=true
      - GRAPHS1090_DARKMODE=true
      # Prometheus and InfluxDB connection parameters:
      # - INFLUXDBV2_URL=${INFLUX_URL}
      # - INFLUXDBV2_TOKEN=${INFLUX_TOKEN}
      # - INFLUXDBV2_BUCKET=${INFLUX_BUCKET}
      # - PROMETHEUS_ENABLE=true
    volumes:
      # - /opt/adsb/ultrafeeder/globe_history:/var/globe_history
      # - /opt/adsb/ultrafeeder/graphs1090:/var/lib/collectd
      - /proc/diskstats:/proc/diskstats:ro
      - /dev/bus/usb:/dev/bus/usb
    tmpfs:
      - /run:exec,size=256M
      - /tmp:size=128M
      - /var/log:size=32M
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    name: web
    external: true
