services:
  owrxplus:
    image: "slechev/openwebrxplus-softmbe:latest"
    container_name: owrx-mbe
    ports:
      - "127.0.0.1:8073:8073"
    environment:
      TZ: Asia/Kolkata
      OPENWEBRX_ADMIN_USER: admin
      OPENWEBRX_ADMIN_PASSWORD: admin
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - openwebrx_settings:/var/lib/openwebrx
      # - /opt/owrx-docker/etc:/etc/openwebrx
    tmpfs:
      - /tmp:mode=1777
    restart: unless-stopped
    networks:
      - web

volumes:
  openwebrx_settings: {}

networks:
  web:
    name: web
